### ISSUE TITLE
seting memory_limit

### ISSUE THREAD

**Issue by teresa-m** [smautner/biofilm#1]
I had the following errors running biofilm.biofilm-optimize6

init_dgesdd failed init
init_dgesdd failed init
init_dgesdd failed init

Your auto autosklearn classification call has the memory_limit at the moment hardcoded to 240000/30. 
However, my cloud instance does not have (14*8000) GB Ram. Could you please make an input parameter here? Hope this will fix this issue. Thanks a lot for your help.

**Comment by smautner** [comment]
v0.0.81 is now on conda and pypi!
